package com.localdeals.utils;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Pattern;

/** Canonicalizes paths generated by the managed blog-image upload endpoint. */
public final class ManagedImagePath {

    private static final Pattern PATTERN = Pattern.compile(
            "^blogs/(?:[0-9]|1[0-5])/(?:[0-9]|1[0-5])/" +
                    "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.(?:jpg|jpeg|png)$"
    );

    private ManagedImagePath() {
    }

    public static String normalize(String filename) {
        if (filename == null) {
            return null;
        }
        String normalized = filename.trim().replace('\\', '/');
        if (normalized.startsWith("/imgs/")) {
            normalized = normalized.substring("/imgs/".length());
        } else if (normalized.startsWith("/")) {
            normalized = normalized.substring(1);
        }
        try {
            Path relativePath = Paths.get(normalized).normalize();
            if (relativePath.isAbsolute() || relativePath.startsWith("..")) {
                return null;
            }
            String relativeName = relativePath.toString().replace('\\', '/');
            return PATTERN.matcher(relativeName).matches() ? relativeName : null;
        } catch (RuntimeException e) {
            return null;
        }
    }
}
